apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-runtime
  namespace: mikasmissions-dev
data:
  GO_ENV: production
  PERSISTENCE_MODE: strict
  AUTH_MODE: enforce
  LOG_LEVEL: info
  NATS_URL: nats://nats:4222
  TEMPORAL_HOSTPORT: temporal:7233
  IDENTITY_URL: http://identity-service
  PROFILE_URL: http://profile-service
  CATALOG_URL: http://catalog-service
  RECOMMENDATION_URL: http://recommendation-service
  PLAYBACK_URL: http://playback-service
  PROGRESS_URL: http://progress-service
  CREATOR_URL: http://creator-studio-service
  BILLING_URL: http://billing-service
  ADMIN_STUDIO_URL: http://admin-studio-service
